### ISSUE TITLE
no signatureVersion

### ISSUE THREAD

**Issue by fedeghe** [cloudconvert/cloudconvert-node#10]
When I try to output on aws s3, there seems to be no way to specify the `signatureVersion: 'v4'`
,then i get always
**CloudConvert Process failed: Error: Saving to S3 failed: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Code: InvalidRequest)**

**Comment by josiasmontag** [comment]
It should automatically always choose the latest signature version if possible. This error most likely means that there is something wrong with your accessKey / keyId / bucket name combination. Please send a full example request to support@cloudconvert.com.

**Comment by fedeghe** [comment]
Unluckily I can`t send a full example but luckily a simple work-aroud solve it  just making one more step using aws-sdk to save on s3 after getting from cloud-convert the urls for the converted media... thx anyway for the fast reply!
