### ISSUE TITLE
Is it possible to deine a content_type header ?

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#107]
When using the 'export/s3' operation, is it possible to add a content_type option, the same as the content-disposition.
I'm trying to force aws to download the file instead of opening it, since the content-type is automatically set "application/pdf" and I'm trying to change it "binary/octet-stream".
The problem is even though I defining it in the metadata object, it treats it as a custom header, as shown in the screenshot below.
Anything you guys can help with ?

![Capture d’écran 2023-10-03 à 12 39 35](https://github.com/cloudconvert/cloudconvert-node/assets/4510058/76096cbd-f713-4eed-8fed-dfb83f464740)

**Comment by josiasmontag** [comment]
You currently cannot override the ContentType. This is a limitation of the CloudConvert API itself, not of the node SDK. As a customer you might contact the CloudConvert support with a feature request.
