### ISSUE TITLE
created process = null ?

### ISSUE THREAD

**Issue by daslicht** [cloudconvert/cloudconvert-node#11]
Hi,
when I create a process like the following , the returned process is just null:
```
var fs = require('fs'),
    cloudconvert = new (require('cloudconvert'))('MY-API-KEY');
 
cloudconvert.createProcess({
    "inputformat": "flv",
    "outputformat": "mp4"
}, function(process) {
     // process = null
});
```

How to debug ? please?

**Comment by josiasmontag** [comment]
The first parameter of the callback is `err`, not `process`.
```js
cloudconvert.createProcess({inputformat: 'png', outputformat: 'pdf'}, function(err, process) {});
```

**Comment by daslicht** [comment]
Interesting, in that case I found an error in the cloud conversion docs : 

https://cloudconvert.com/api/conversions#introduction

**Comment by josiasmontag** [comment]
Thanks, we will fix that.

**Comment by daslicht** [comment]
Thanks !
