### ISSUE TITLE
import/upload task failing with wrong upload url

### ISSUE THREAD

**Issue by krazylearner** [cloudconvert/cloudconvert-node#114]
I am not sure what is changed but after task is created , I am not able to upload file
```
{
      id: 'f714be14-d3ac-4f2a-93bd-ad27cc6cd759',
      name: 'import-my-file',
      job_id: 'dcddbecd-1526-4540-880d-814c88009663',
      status: 'waiting',
      credits: null,
      code: null,
      message: 'Waiting for file upload',
      percent: 100,
      operation: 'import/upload',
      result: {
        form: {
          url: 'https://cloudconvert-files-us-east.s3.amazonaws.com',
          parameters: [Object]
        }
      },
      created_at: '2024-03-05T08:08:05+00:00',
      started_at: null,
      ended_at: null,
      retry_of_task_id: null,
      copy_of_task_id: null,
      user_id: 15003317,
      priority: 10,
      host_name: null,
      storage: 's3-us-east-1',
      region: 'us-east',
      depends_on_task_ids: [],
      links: {
        self: 'https://api.cloudconvert.com/v2/tasks/f714be14-d3ac-4f2a-93bd-ad27cc6cd759'
      }
    }
```

I am getting this error when I try to upload file on this url _**https://cloudconvert-files-us-east.s3.amazonaws.com**_

<Error><Code>InvalidArgument</Code><Message>Unsupported Authorization Type</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer jjj</ArgumentValue><RequestId>2HTRYAXR7M30Q3Q6</RequestId><HostId>jthB0yx2PE9xXyFBQ0Y3dM30XqDHf3qy4j5GNjqo1pJuQnjMSik1+Kip8uFdtZwH7nMq6CKszE8=</HostId></Error>

Even the example in docs is pointing to differrent url which is **_https://upload.cloudconvert.com/_**

Everything was working fine before.

**Comment by josiasmontag** [comment]
It seems you are using a custom implementation and not this SDK.
This is an issue tracker for the SDK and should not be used for support requests.

**Comment by krazylearner** [comment]
@josiasmontag Yes I am not using SDK but the platform is node.js. Please can you guide me where to create support requests ? I am pretty lost here.

Regards

**Comment by josiasmontag** [comment]
Support: https://cloudconvert.com/contact

Please consider using the SDK instead of a custom implementation. It has implemented this already and there is no need to reinvent the wheel. Other than that you can have a look at the source code of the SDK.
