### ISSUE TITLE
Multiple outputs for one job ?

### ISSUE THREAD

**Issue by daslicht** [cloudconvert/cloudconvert-node#13]
Hi,
is there a way to define multiple outputs for one input file , or do I have to manually implement that kind of feature, please?

e.g.:
input: 
```video.mp4 ```

output:
```video_thumb.jpg```
```video.webm```
```video.ogv```

**Comment by josiasmontag** [comment]
This is not supported by CloudConvert. You need to build this using your custom implementation.
