### ISSUE TITLE
Callback sometimes called twice when converting to and from S3

### ISSUE THREAD

**Issue by otusweb** [cloudconvert/cloudconvert-node#14]
I'm converting multipage PDF to jpeg and on a 2 page PDF, the callback is sometimes called twice.

Here is the code I use:

`cloudconvert.convert({
    "inputformat": "pdf",
    "outputformat": "jpg",
    "input": {
      "s3": {
        "accesskeyid": cloudConvertDownloadUserId,
        "secretaccesskey": cloudConvertDownloadSecretAccessKey,
        "bucket": S3_BUCKET
      }
    },
    "file": presentation.pdfURL.replace("https://" + S3_BUCKET + ".s3.amazonaws.com/", ''),
    "output": {
      "s3": {
        "accesskeyid": cloudConvertUploadUserId,
        "secretaccesskey": cloudConvertUploadSecretAccessKey,
        "bucket": S3_BUCKET,
        "path": s3SlidesFolder + "/",
        "acl": "public-read"
      }
    }
  }, function (err, process) {console.log("complete")});`

**Comment by josiasmontag** [comment]
Should be solved with the current dev version. Can you check?
