### ISSUE TITLE
wait don't work

### ISSUE THREAD

**Issue by tthil** [cloudconvert/cloudconvert-node#15]
I try to call cloudconvert-node with this parameters:

 cloudconvert.convert({
    inputformat: 'html',
    outputformat: 'docx',
    input: 'base64',
    wait: true,
    download: false,
    file: base64.fileBase64,
    filename: `${tripKey}.html`
  })
    .pipe(Write.stream(`../../docs/${tripKey}.doc`)
    .on('finish', () => (console.log('1'))));
  console.log('2');
  return { url: `/assets/docs/${tripKey}.doc` };

console.log('2') always happens before console.log('1')

How could I make the call wait until convert is done?

//Thomas

**Comment by josiasmontag** [comment]
`cloudconvert.convert()` is always async. If you really need a sync function, you could use something link [deasync.js](https://github.com/abbr/deasync).
