### ISSUE TITLE
Finished event never called

### ISSUE THREAD

**Issue by xonuzofa** [cloudconvert/cloudconvert-node#16]
Event is never called.  Output is always blank.

    let api = 'my secret';
    let cloudconvert = new (require('cloudconvert'))(api);
						
    cloudconvert.createProcess({
        "mode": "combine",
        "inputformat": "pdf",
        "outputformat": "pdf"
    }, (err, cloudProcess) => {
							
        console.log(cloudProcess);
        if (cloudProcess.url) {
            cloudProcess.start({
                "mode": "combine",
		"input": "download",
		"files": [							
                    "https://cloudconvert.com/assets/11e13801/testfiles/pdfexample1.pdf",
                    "https://cloudconvert.com/assets/11e13801/testfiles/pdfexample2.pdf"
                ],
                "outputformat": "pdf"
            })
            .on('error', (err) => {
                console.log(err);
            })
            .on('finished', (data) => {
                console.log('Done: ' + data.message);
            })
            .on('started', () => {
                console.log('Started');
            })
            .on('downloaded', () => {
                console.log('downloaded');
            }).pipe(fs.createWriteStream('outputfile.pdf'));
        }

The conversion is counted on my dashboard but nothing is written to outputfile.pdf (it is blank).  Only the started event gets called, none of the other events are ever called.  What is wrong?

**Comment by josiasmontag** [comment]
Were you able to solve the issue? If yes, how?

**Comment by xonuzofa** [comment]
Yes.  Basically the process that comes from the callback of the createprocess function does not show events and calling pipe on it does not output anything.  Simply changing this to use the process which comes from the callback of the process.start function is what you need to use.

    let cloudconvert = new (require('cloudconvert'))(Meteor.settings['galaxy.meteor.com'].env['CLOUDCONVERT']);
						
    cloudconvert.createProcess({
        "mode": "combine",
        "inputformat": "pdf",
        "outputformat": "pdf"
    }, (err, cloudProcess) => {
        if (cloudProcess.url) {
            cloudProcess.start({
                "mode": "combine",
                "input": "base64",
                "files": fileData,
                "outputformat": "pdf"
            }, (err, res) => {
                res.pipe(fs.createWriteStream(folderPath + '/combined.pdf'));

                res.on('downloaded', (data) => {
                    let buff = fs.readFileSync(folderPath + '/combined.pdf', 'base64');
                    future.return('data:application/pdf;base64,' + buff);
                    rmDir(folderPath);
                    res.delete();
                });
            });
        }
        else {
            console.log('no url');
            rmDir(folderPath);
            future.return('');
        }
    });
