### ISSUE TITLE
Non latin characters in file name

### ISSUE THREAD

**Issue by vnxdev** [cloudconvert/cloudconvert-node#19]
When using non-latin characters (in my case Cyrillic) in file name I end up with converted file names like this ` ÐÐÐ¡Ð¢.pdf`
I am using `'input': 'download'` and `output': {'s3'...`
It would be useful if you could add output filename option to explicitly set resulting filename or use transliteration on input file names

**Comment by josiasmontag** [comment]
This seems to be an issue with the conversion type. What is the input format and the output format of your conversions?

**Comment by vnxdev** [comment]
Input format **docx**, output **pdf**

**Comment by vnxdev** [comment]
Hey, any updates on this? I can reproduce this bug and tell you my account name so that you could check it out.

**Comment by josiasmontag** [comment]
Does the same happen on the CloudConvert website? Also, please use the "Send feedback" button for one problematic conversion and reference to this issue. Thanks!
![image](https://user-images.githubusercontent.com/1945577/30773311-b49a9604-a06e-11e7-9487-b60e4109fe8d.png)

**Comment by vnxdev** [comment]
When I upload the file via website - filename displays correctly.

I couldn't send feedback on problematic conversion because I don't have a button (file is saved to S3):

<img width="636" alt="screen shot 2017-09-23 at 16 03 11" src="https://user-images.githubusercontent.com/9074938/30773423-ef505770-a078-11e7-88e1-9ba908fe9bd7.png">

My account name on CloudConvert is username18

**Comment by josiasmontag** [comment]
Please try to override the input filename using the `filename` parameter:
```json
{
    "outputformat": "pdf",
    "filename": "ЛИСТ КИРИЛЛИЦА.docx",
    "file": "http://...",
...
}
```

**Comment by vnxdev** [comment]
Yes, I can use this approach and parse/set input filename from url but isn't this a bug after all? :-)

**Comment by josiasmontag** [comment]
Indeed this seems to be a bug, which we will address. In the meantime you can use the mentioned workaround.

**Comment by josiasmontag** [comment]
Problem should be solved now. If there are still issues, feel free to comment/reopen.
