### ISSUE TITLE
Process expects stream to originate from fs.createReadStream

### ISSUE THREAD

**Issue by joostverdoorn** [cloudconvert/cloudconvert-node#2]
I have a stream that doesn't originate from the filesystem, which I want to pipe through cloudconvert. However, Process wants to `stat` the originating file to emit progress updates which depend on the size of the file to be uploaded. This is not possible with arbitrary streams, only with ones originating from `fs`.

See the following lines:
https://github.com/cloudconvert/cloudconvert-node/blob/master/lib/process.js#L126
https://github.com/cloudconvert/cloudconvert-node/blob/master/lib/process.js#L131

If necessary, I can provide a PR which solves this issue.

**Comment by josiasmontag** [comment]
Thanks for your report. A PR for fixing this would be highly appreciated.

**Comment by joostverdoorn** [comment]
This has proven more difficult than expected. Although removing dependency on `this._source.path` isn't that hard, the `form-data` package used by `request` expects streams to have a definite length, or to have the length set manually. 

I've settled for writing my stream to a tempfile before piping it through cloudconvert. This would still be a nice feature, but has no priorities for me.

**Comment by AlmaasAre** [comment]
+1

**Comment by josiasmontag** [comment]
The latest update supports non-file as input streams:

```js
var api = new cloudconvert(process.env.API_KEY);

var stringStream = new stream.Readable();
stringStream.push('<html><head></head><body><h1>test</h1></body></html>');
stringStream.push(null);
        
stringStream.pipe(api.convert({
            inputformat: 'html',
            outputformat: 'pdf',
})).pipe(fs.createWriteStream(__dirname  + '/out.pdf'));
```

**Comment by joostverdoorn** [comment]
@josiasmontag awesome! Thanks a lot, this really helps my use case.

**Comment by Rahul-Jagga** [comment]
i have big issue i dont know how to fix it.I am using cloud convert for file conversion , after file conversion i got the some files of convert files.
example : i put the ppt and then convert into jpg images in destination show all images but in html container shows only 11 or 12 images from of convert file.
please help as soon as possible.

**Comment by josiasmontag** [comment]
@Rahul-Jagga This seems to be a problem of your custom implementation and is not related to this issue. Please do not use this thread. Also, you don't need to unzip the file, have a look at the ``downloadAll()``method.

**Comment by seyfer** [comment]
is it possible to do the same in PHP without saving and reading a file?
