### ISSUE TITLE
Allow passing in resize width, height and DPI as integers

### ISSUE THREAD

**Issue by juho** [cloudconvert/cloudconvert-node#23]
Instead of passing in a string like `1024x768`, resize width and height should be an integer (maybe just `width` and `height` params). Also DPI should be a param.

**Comment by josiasmontag** [comment]
The DPI converter option is named `density`. 

I agree that this is not optimal. However, this is a general issue with our API v1 which we cannot change without breaking existing implementations.

We are currently working on API v2 which will solve this and uses more consistent parameters.

**Comment by juho** [comment]
Ah thanks, missed `density` :)
