### ISSUE TITLE
Allow defining if zip file on Cloudconvert should be created when using S3

### ISSUE THREAD

**Issue by juho** [cloudconvert/cloudconvert-node#24]
We don't want any files stored on Cloudconvert, just stored straight to our bucket. Having the files display on the dashboard is a security concern.

Just passing in a param to ignore the uploaded file in the Cloudconvert system would be the easiest I think. `output.save` seems to not apply here?

**Comment by josiasmontag** [comment]
As long as you don't opt in with the `save` option, no file will be stored on CloudConvert. It will show your process in the CloudConvert UI though, but only the metadata is stored on our end. If you want to remove this as well, you can manually delete the process using `process.delete()`.

Does this answer your question?

**Comment by juho** [comment]
Would it be possible to just pass it as a parameter without having to call `delete`? That'd be the best I think. The less dominoes to call the better IMHO.

**Comment by josiasmontag** [comment]
I don't think this is a reasonable feature. There is nothing wrong abut using a separate `delete()` call for this.
