### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [cloudconvert/cloudconvert-node#30]
I found range error : array buffer allocation failed at cloudconvert/node_modules/request/request.js:1135:30

**Comment by Kyaw-Zin-Thant** [comment]
My upload file size is 61.2mb

**Comment by josiasmontag** [comment]
I am closing this because the issue is related to the old v1 SDK. If you still have this problem with v2, feel free to open a new issue.
