### ISSUE TITLE
Support for async/await

### ISSUE THREAD

**Issue by andywgarcia** [cloudconvert/cloudconvert-node#32]
Is there support for async await? I am using this in a lambda function and I need the container to stay alive until this process is complete because it is a synchronous conversion. I am currently using the async/await pattern everywhere else, so I need to be able to await for a process id.

**Comment by josiasmontag** [comment]
The current node wrapper uses the callback style. You could something like [Bluebird promisfyAll()](http://bluebirdjs.com/docs/api/promise.promisifyall.html) to convert these to Promises.

The next major version of this SDK will have full native async/await support.

**Comment by josiasmontag** [comment]
The [v2 branch](https://github.com/cloudconvert/cloudconvert-node/tree/v2) has async/await support.
