### ISSUE TITLE
How to get the uploaded file(s) to s3 after conversion ?

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#34]
I'm successfully converting a .pptx file into thumbnails.
Problem is that I need to have the converted files "url, bucket, key" as part of my response.
So far went through the documentation and wasn't successful in "finding" a response.

Am I missing something ?

**Comment by josiasmontag** [comment]
You can get all available process data via `process.data`. It does not contain the bucket and key though, but you should know that because you have sent it when starting the request?

By default S3 objects do not have public URLs. You would need to create them manually using the AWS SDK.
