### ISSUE TITLE
Conversion type not supported: zip to ? (mode info)

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#35]
I'd like to know if I'm doing something wrong here with me trying to extract a ".zip" file.

```js
cloudConvert.createProcess({
            "inputformat": "zip",
            "outputformat": "*",
            "mode": "extract"
        }, (error, process) => {
            console.log(error)
      });
```
Please do not mind any missing "), }".
No errors when I run this code.
The problem shows on the dashboard

"Conversion type not supported: zip to ? (mode info)".

No idea what I'm doing wrong, I've tried the Api with 
```js
cloudconvert.convert({})
```
 but since I'm using the createProcess method here, maybe I'm going about it in a wrong way.

Cheers.

**Comment by josiasmontag** [comment]
The problem here are the parameters of your `process.start()` call. You need to provide `mode` here as well.

**Comment by minedun6** [comment]
Much appreciated.

Is it possible to add this to the documentation or to mention it ?

**Comment by josiasmontag** [comment]
It is already. See [here](https://cloudconvert.com/api/v1/combine).
