### ISSUE TITLE
extracting .zip file content to another subdirectory ?

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#37]
Related issue is closed #36 

> You would need to handle that on your end using the S3 SDK.

Any ideas/advices on how I would need to handle this ?

PS: please don't close the issue this time as I might need to respond if necessary.
Otherwise I'll close the issue myself.

Cheers.

**Comment by josiasmontag** [comment]
You could rename the keys when the conversion is finished (using a webhook). 

This is an issue tracker for the node SDK. Please understand that this issue tracker is not intended to be used for [support requests](https://cloudconvert.com/contact).
