### ISSUE TITLE
How to use api link to convert html to pdf

### ISSUE THREAD

**Issue by joelwass** [cloudconvert/cloudconvert-node#4]
How can I convert a local html file to a pdf file and return it to the client? 

Conversion is fine, however returning it to the client vs. downloading it onto my server has been the issue. Any advice? I want it to download for the client, much like the api console example does when you upload a file manually.

**Comment by josiasmontag** [comment]
```js
fs.createReadStream('input.html').pipe(cloudconvert.convert({
    inputformat: 'html',
    outputformat: 'pdf',
}).on('finished', function(data) {
    console.log('Redirect user to: ' + data.output.url);
}));
```
Should do it.

**Comment by joelwass** [comment]
Much appreciation for the quick reply. solved immediately. Surprised they didn't mention this at all in the api documentation. thanks again
