### ISSUE TITLE
Get file info (not yet | no longer) available

### ISSUE THREAD

**Issue by KnorpelSenf** [cloudconvert/cloudconvert-node#41]
API v1 supported [getting file information](https://cloudconvert.com/api/v1/info).
I see no way how to do this with v2. Also, v1 returns a 500 error nowadays.

Is this feature silently being discontinued? If so, please provide further information on why this is the case. Also, please take down the documentation linked above as it is outdated then.

If the feature is still supported, please
a) fix the issue with v1 and
b) provide the documentation & implementation.

**Comment by josiasmontag** [comment]
The feature is available and not "silently discontinued". Please provide exact request payload and the complete response body you are getting.

**Comment by KnorpelSenf** [comment]
I have code running in production that used to work fine for a long time until I discovered recently that this feature no longer works. I did not make any code changes.
As the code was pretty hacky, I decided to rewrite things with v2 so I can use it as soon as it get stable, however, that does not seem possible yet as the endpoints are missing.

I extracted the relevant code snippet in Node.js. It relies on `"cloudconvert": "^1.1.2"` as stated in package.json. Here it is:
```jslet from = 'pdf';
let url = '...'; // url to my pdf file
cloudconvert.createProcess({
    'inputformat': from,
    'outputformat': from,
    'mode': 'info'
}, (err, process) => {
    process.start({
        'mode': 'info',
        'input': 'download',
        'file': url
    }, (err, process) => {
        process.wait((err, process) => {
            let info = process.data.info;
            for (key in info) {
                console.log(' +++ ' + key + ' +++')
                console.log(info[key]);
            }
        });
    });
});
```

**Comment by josiasmontag** [comment]
For further debugging we would need the exact request payload and response. As this issue is not directly related to the node SDK, it would be better to contact support@cloudconvert.com with these details. Please also provide your account name.
