### ISSUE TITLE
Problem with create import/upload jobs

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#43]
Hi,
I'm playing with the new v2 api and I'm trying to piece things together.
Problem is when I'm trying to upload a local file, there seems to be a problem.
On my dashboard, I see the job in "waiting" but nothing else happens.
Especially since the file is relatively small in size so the "upload" task should be quick.

Here's the code I'm doing.

```js
const job = await cloudConvert.jobs.create({
            tasks: {
                import: {
                    operation: 'import/upload',
                    file: "index.html"
                }
            }
        });
``` 

I've stripped the convert/export task since the issue seems to be related to the import part.
the "index.html" file is in the root of the folder I'm working on.

By the way, the same file works just fine when I use the v1.

**Comment by josiasmontag** [comment]
Please see the README: https://github.com/cloudconvert/cloudconvert-node#uploading-files

Jobs need to be created without the `file` key. Afterwards, files are uploaded with a separate request.

**Comment by minedun6** [comment]
Yes, thank you very much for the prompt reply.
Indeed, the answer was right in front of me and I really didn't see.
Sorry for the wasted time and again, thank you :)
