### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by magoz** [cloudconvert/cloudconvert-node#45]
Could you add types / TypeScript definitions?

**Comment by KnorpelSenf** [comment]
@magoz @Suyashtnt could you review my PR and validate that the proposed changes integrate into your TypeScript workflow without causing problems?

**Comment by Suyashtnt** [comment]
> 
> 
> @magoz @Suyashtnt could you review my PR and validate that the proposed changes integrate into your TypeScript workflow without causing problems?

ok ill see

**Comment by jaymathew** [comment]
I'm building a typescript project that includes cloud convert and this is the only non-typescript Libaray. I would like to see this added.

**Comment by KnorpelSenf** [comment]
@jaymathew if you can try out the proposed changes in #46 and validate that they work, I can complete the work on the migration to typescript later today.
