### ISSUE TITLE
Inconsistent docs

### ISSUE THREAD

**Issue by KnorpelSenf** [cloudconvert/cloudconvert-node#47]
The [website with the socket API specs](https://cloudconvert.com/api/v2/socket#socket) defines four event types for jobs and tasks:
- `created`
- `updated`
- `finished`
- `failed`.

In contrast, the README file declares five possible event types:
- `created`
- `updated`
- `finished`
- `error`
- `deleted`.

This is inconsistent. Which version is correct?

No other API client software implements the websocket protocol, therefore I cannot find a third reference. Please fix this so I can properly type the events when working on #46.

**Comment by josiasmontag** [comment]
The API docs are correct. I fixed the README in the master branch.
Thanks.
