### ISSUE TITLE
How to set a sandbox mode?

### ISSUE THREAD

**Issue by sofikarp** [cloudconvert/cloudconvert-node#48]
Hi, I'm trying to use CloudConvert api v2 and upload a file.

    async convert(file: string, imageType: ImageType) {
      const cloudConvert = new CloudConvert(process.env.API_KEY);

       const job = await cloudConvert.jobs.create({
         tasks: {
          'upload': {
            operation: 'import/upload'
          }
        }
      });

      const uploadTask = job.tasks.filter(task => task.name === taskName)[0];
      const inputFile = fs.createReadStream(file);
      return await cloudConvert.tasks.upload(uploadTask, inputFile);
    }

I'm trying to use sandbox (I have a sanbox API key and a whitelisted file), but I'm getting 401.
In the CloudConvert documentation there is stated that https://api.sandbox.cloudconvert.com should be used, but I can see in the response the production API is being used instead. How to point the nodejs lib to use sandbox?

Thanks

**Comment by josiasmontag** [comment]
Second parameter of the constructor should be `true` to use the Sandbox API.
```js
const cloudConvert = new CloudConvert(process.env.API_KEY, true);
```

**Comment by sofikarp** [comment]
> Second parameter of the constructor should be `true` to use the Sandbox API.
> 
> ```js
> const cloudConvert = new CloudConvert(process.env.API_KEY, true);
> ```

Working, thanks!
