### ISSUE TITLE
throw new Error('Output not (yet) available')

### ISSUE THREAD

**Issue by adeel-raza** [cloudconvert/cloudconvert-node#5]
This is my code It's showing this error. 

var fs = require('fs'),
    cloudconvert = new (require('cloudconvert'))(api_key);
 
fs.createReadStream('filename.jpg')
.pipe(cloudconvert.convert({
    "inputformat": "jpg",
    "outputformat": "png",
    "input": "upload",
    "output": "dropbox"
}))
.pipe(fs.createWriteStream('filename.png'))

**Comment by josiasmontag** [comment]
The problem with your code is that the output file is directly saved to Dropbox and is not available for download.
If you need it as download anyways, please add
``'save': 'true'``
to your ``convert()`` parameters.
