### ISSUE TITLE
Trouble with node client

### ISSUE THREAD

**Issue by jaymathew** [cloudconvert/cloudconvert-node#50]
I am having trouble creating a job in Node. What is odd is I can copy these tasks and API key and run them just fine in Postman.   

In node I am receiving a 401 status code. I even tried generating a new key with same result.  In Postman this key works. 

      `import CloudConvert from 'cloudconvert';
        const cloudConvert = new CloudConvert('sandBoxAPIKey');

         async function convert(){

              try {
        
        const job = await cloudConvert.jobs.create({
            "tasks": {
                "importConvertVideo": {
                    "operation": "import/url",
                    "url": "https://urlToFile",
                    "filename": "IMG_0090.MOV",
                    "headers": {
                        "companyID": 101,
                        "projectID": 102
                    }
                },
                "taskConvertVideo": {
                    "operation": "convert",
                    "input_format": "mov",
                    "output_format": "mp4",
                    "engine": "ffmpeg",
                    "input": [
                        "importConvertVideo"
                    ],
                    "video_codec": "x264",
                    "crf": 23,
                    "preset": "fast",
                    "audio_codec": "aac",
                    "audio_bitrate": 128,
                    "engine_version": "4.1.4"
                },
                "exportConvertVideo": {
                    "operation": "export/url",
                    "input": [
                        "taskConvertVideo"
                    ],
                    "inline": false,
                    "archive_multiple_files": false
                }
            }
        });

    } catch (error) {
        console.log("error: ", error)
    }
     
     }

     convert()`

**Comment by josiasmontag** [comment]
If you want to use the Sandbox API, you need to set the second parameter of the constructor to `true`.

```js
const cloudConvert = new CloudConvert('sandBoxAPIKey', true);
```

**Comment by jaymathew** [comment]
thank you that worked. I must have missed that in the docs.
