### ISSUE TITLE
Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by developerKumar** [cloudconvert/cloudconvert-node#58]
I am getting error as "Request body larger than maxBodyLength limit". While uploading file from local.

**Code;** 

`let job = await cloudConvert.jobs.create({
    "tasks": {
        "upload-webm": {
            "operation": "import/upload"
        },
        "webm-to-mp4": {
            "operation": "convert",
            "input_format": "webm",
            "output_format": "mp4",
            "engine": "ffmpeg",
            "input": [
                "upload-webm"
            ],
            "video_codec": "x264",
            "crf": 23,
            "preset": "medium",
            "subtitles_mode": "none",
            "audio_codec": "aac",
            "audio_bitrate": 128,
            "engine_version": "4.1.4"
        },
        "export-mp4-to-s3": {
            "operation": "export/s3",
            "input": [
                "webm-to-mp4"
            ],
            "bucket": "xxxx",
            "region": "xxxx",
            "access_key_id": "xxxx",
            "secret_access_key": "xxxx",
            "key": s3FileKey,
            "acl": "authenticated-read"
        }
    }
});

const uploadTask = job.tasks.filter(task => task.name === 'upload-webm')[0];

const inputFile = fs.createReadStream(__dirname + '/' + fileName);
console.log('InputFile =>', inputFile)

await cloudConvert.tasks.upload(uploadTask, inputFile, fileName.replace('../library/', ''));`

**Below are the error details:**

ERROR cloudconvert =>  Error: Request body larger than maxBodyLength limit
   
  config: {
    url: 'https://storage.de.cloud.ovh.net/v1xxxxxx/cloudconvert-files/a35659a7-99de-4a47-9f07-0a451d106da9/',
    method: 'post',
    data: FormData {
      _overheadLength: 837,
      _valueLength: 151,
      _valuesToMeasure: [Array],
      writable: true,
      readable: true,
      dataSize: 0,
      maxDataSize: 2097152,
      pauseStreams: true,
      _released: true,
      _streams: [Array],
      _currentStream: [DelayedStream],
      _insideLoop: false,
      _pendingNext: false,
      _boundary: '--------------------------978290168414846072467162',
      _events: [Object: null prototype],
      _eventsCount: 3
    },
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data; boundary=--------------------------978290168414846072467162',
      Authorization: {},
      'User-Agent': 'cloudconvert-node/v2 (https://github.com/cloudconvert/cloudconvert-node)',
      maxContentLength: Infinity,
      maxBodyLength: Infinity
    },
    baseURL: 'https://api.cloudconvert.com/v2/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: false,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/v1/xxxxxx/cloudconvert-files/a35659a7-99de-4a47-9f07-0a451d106da9/',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'storage.de.cloud.ovh.net',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/Axxxxxx/cloudconvert-files/a35659a7-99de-4a47-9f07-0a451d106da9/'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 10470226,
    _requestBodyBuffers: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 79 more items
    ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: true,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /v1/xxxxx/cloudconvert-files/a35659a7-99de-4a47-9f07-0a451d106da9/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: multipart/form-data; boundary=--------------------------978290168414846072467162\r\n' +
        'Authorization: [object Object]\r\n' +
        'User-Agent: cloudconvert-node/v2 (https://github.com/cloudconvert/cloudconvert-node)\r\n' +
        'maxContentLength: Infinity\r\n' +
        'maxBodyLength: Infinity\r\n' +
        'Host: storage.de.cloud.ovh.net\r\n' +
        'Connection: close\r\n' +
        'Transfer-Encoding: chunked\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/xxxxxx/cloudconvert-files/a35659a7-99de-4a47-9f07-0a451d106da9/',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: true,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://storage.de.cloud.ovh.net/v1/xxxxx/a35659a7-99de-4a47-9f07-0a451d106da9/',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}

I have manually tried giving maxBodyLength and maxContentLength headers, but it didn't work.

Can please help here ? Thanks

**Comment by josiasmontag** [comment]
Can you check if the latest [patch](https://github.com/cloudconvert/cloudconvert-node/commit/d154e5373153e535c24d651ee63be9639f855741) on master solves the issue?

**Comment by josiasmontag** [comment]
Should be fixed with version 2.1.4.
