### ISSUE TITLE
uploading issue

### ISSUE THREAD

**Issue by Rahul-Jagga** [cloudconvert/cloudconvert-node#6]
i am using your code.The issue is getting the images after convert the file.i upload the ppt file convert it. everthing is working fine till that but when process finished i show these all file in a container but the process shows only some file.
example : i upload the ppt file convert it on put into destination folder.In destination folder showing the 16 images but in container show only 12 images.
and while i upload docs files it makes images but shows only 3 images
thats the issue with us can anybody help as soon as
thanks.

**Comment by Rahul-Jagga** [comment]
hello sir,
i want to make the process counter and show at the time of processing  of uploading the files on client side . Can anybody tell me how i can do this

**Comment by josiasmontag** [comment]
You are mixing two different issues here. Also, I do not completely get your point. Closing this issue here because it seems to be not directly related to the wrapper. To get help please contact support@cloudconvert.com with code snippets and logs.
