### ISSUE TITLE
Quick start example typo

### ISSUE THREAD

**Issue by ozooner** [cloudconvert/cloudconvert-node#7]
Firstly, thanks for the library! I wanted to note that there is a bracket missing in the quick start example (see bold bracket):
fs.createReadStream('tests/input.png')
.pipe(cloudconvert.convert({
    inputformat: 'png',
    outputformat: 'jpg',
    converteroptions: {
        quality : 75,
    }
 }))
.pipe(fs.createWriteStream('out.jpg')**)**
.on('finish', function() {
    console.log('Done!');
});

**Comment by josiasmontag** [comment]
Thanks!
