### ISSUE TITLE
Cancel task is not implemented

### ISSUE THREAD

**Issue by rennehir** [cloudconvert/cloudconvert-node#70]
When using this library we noticed that canceling a task is not implemented in the `TasksResource.ts` even though it is available in the API.

We ended up using the axios instance in our project to make the API call to cancel a task.

Example:
```javascript
await cloudConvert.axios.post(`tasks/${task.id}/cancel`)
```

This should be pretty straightforward to implement in the library as well.

**Comment by josiasmontag** [comment]
Added in version 2.2.0.
