### ISSUE TITLE
Property 'socket' is private and only accessible within class 'CloudConvert'.

### ISSUE THREAD

**Issue by rennehir** [cloudconvert/cloudconvert-node#71]
The docs for the [websocket events](https://github.com/cloudconvert/cloudconvert-node#websocket-events) state that when one doesn't want to receive any events anymore, they should close the socket.

Though, `cloudConvert.socket` is defined as a private property and should be called only from within the class, which results in TypeScript errors. So the docs are inconsistent with the actual implementation.

![image](https://user-images.githubusercontent.com/24566763/109129764-ab05a280-7759-11eb-928a-8da33c5df519.png)

Possible solutions could be setting the socket public (probably not a good idea) or adding a method to `CloudConvert` class that closes the socket.

**Comment by josiasmontag** [comment]
Version 2.2.0 now has a `cloudConvert.closeSocket()` method.

**Comment by rennehir** [comment]
Awesome, thanks @josiasmontag 👏
