### ISSUE TITLE
Release 2.2.0 broken on npm

### ISSUE THREAD

**Issue by rennehir** [cloudconvert/cloudconvert-node#72]
Upgrading the library to the version 2.2.0 does not work. The directory `built` contains only a `package.json` file and not any of the actual compiled code. See screenshot below.

![image](https://user-images.githubusercontent.com/24566763/109272963-3fcfd500-781a-11eb-9797-459810f76459.png)

I cloned the repo and run `npm run build` and it seemed to be working correctly. Maybe there was an issue with the release process to npm?

**Comment by josiasmontag** [comment]
2.2.1 fixes the package. Sorry for inconvenience.
