### ISSUE TITLE
Issue while importing a pdf file.

### ISSUE THREAD

**Issue by Sameer-hesta** [cloudconvert/cloudconvert-node#74]
I am trying to merge some files Docx and pdfs and create a single pdf,
If I am importing Docx files by URL (import/url) it is working fine but when I try to import a pdf file with the same flow it giver error or Invalid data (**Task import-my-file: The url format is invalid.**)

let job = cloudconvert.jobs.create({
      tasks: {
        'import-my-file': {
          operation: 'import/url',
          url: https://example.pdf
        }
      }
    })

**Comment by josiasmontag** [comment]
How does the URL look like? 
Please make sure it is valid URL according to RFC 3987.

**Comment by Sameer-hesta** [comment]
here is the URL
https://dokkit-deliver-testing.s3.amazonaws.com/dokkit-Victoria Hayden/attachments-stock/pdf.pdf

**Comment by josiasmontag** [comment]
Spaces in URLs are not allowed.

**Comment by Sameer-hesta** [comment]
Thanks,
It is working now without space.
