### ISSUE TITLE
Type "import/raw" is not assignable to type

### ISSUE THREAD

**Issue by mcarson28** [cloudconvert/cloudconvert-node#76]
I'm trying to import a raw file but I'm getting a typescript error that 'import/raw' is not acceptable for the operation field. I built the tasks object from the job builder.  Is raw import no longer supported?

**Comment by josiasmontag** [comment]
The API supports `import/raw` but this SDK has not implemented it yet. We will add that at some point. In meantime, PRs are also welcome :)

**Comment by mcarson28** [comment]
Thanks! I actually think that the upload is going to work better in my case after reading the file size limitations.

**Comment by KnorpelSenf** [comment]
Is this closed by #84?

**Comment by josiasmontag** [comment]
Yes it is.
