### ISSUE TITLE
metadata for google cloud storage not showing up 

### ISSUE THREAD

**Issue by mcarson28** [cloudconvert/cloudconvert-node#77]
I am trying to save a file to google cloud storage with cloudconvert.  I am able to convert and store the file to google cloud storage but when I try to add metadata, it doesn't show up in Google Cloud Storage.  I don't see a metadata field in the GC export object so I tried using a task with the following:

"write-pdf-metadata": {
  "operation": "metadata/write",
  "input": ["upload-pdf"],
  "metadata": {
    "Author": "Richard Hendricks",
    "Title": "The Pied Piper algorithm.",
    "Producer": "CloudConvert",
    "Creator": "CloudConvert"
  },
},

**Comment by josiasmontag** [comment]
You are writing EXIF metadata here, this is not related to Google Cloud Storage object metadata.
Google Cloud Storage object metadata is not supported by the CloudConvert API at this point.

**Comment by mcarson28** [comment]
Ok, thanks for the quick reply!  With Google Cloud Storage, the only way to get a url linked to the file, you have to create a download token which is done by adding metadata.  This can be done after the cloudconvert job runs with the GCP API but it seems like the cloudconvert job completes before the file exists in GCP.  So it requires some additional functions to wait until the file exists.
