### ISSUE TITLE
Words replaced and formating not added in word online

### ISSUE THREAD

**Issue by EmilChigu** [cloudconvert/cloudconvert-node#78]
Hi,

when I convert a pdf to a Docx, words that contain if or ff are replaced with other characters or spaces, for example, office comes out as o3ce in the converted Docx file. 

Secondly when the docx is opened on microsoft word online, all the formating is gone, tables etc.

**Comment by josiasmontag** [comment]
This issue tracker is about the node.js SDK. For issues related to CloudConvert directly please contact support@cloudconvert.com.
