### ISSUE TITLE
Doesn't work behind a corporate proxy

### ISSUE THREAD

**Issue by XmlmXmlmX** [cloudconvert/cloudconvert-node#8]
Please add options to set a proxy. I've already added the [environment variables](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables) `HTTP_PROXY`, `HTTPS_PROXY` with no effect.
### executing this:

```
cloudconvert.convert({
    "inputformat": "eps",
    "outputformat": "svg",
    "input": "upload",
     "file": "src/input.eps"
  })
  .pipe(fs.createWriteStream('outputfile.svg'));
```
### I get this error:

> events.js:141
>      throw er; // Unhandled 'error' event
>      ^
> Error: connect ETIMEDOUT 137.74.133.1:443
>     at Object.exports._errnoException (util.js:907:11)
>     at exports._exceptionWithHostPort (util.js:930:20)
>     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
### executing this:

```
cloudconvert.get('/conversiontypes', {
    inputformat: 'pdf',
    outputformat: 'jpg'
}, function(err, result) {
    if (err) {
        console.log(err);
    } else {
        console.log(result);
    }
});
```
### will log this:

> { [Error: connect ETIMEDOUT 137.74.133.1:443]
>   code: 'ETIMEDOUT',
>   errno: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '137.74.133.1',
>   port: 443 }

**Comment by josiasmontag** [comment]
Hm, if `request` is ignoring the environment variables, this is a `request` issue. We are not doing anything special here. If this issue is still recent and can be fixed in `cloudconvert-node`, feel free to add a PR.
