### ISSUE TITLE
Issue when converting from ppt to pdf [Missing fonts]

### ISSUE THREAD

**Issue by minedun6** [cloudconvert/cloudconvert-node#82]
Sometimes, there seems to be some differences between the original ppt file and the converted pdf file.
I'm guessing there seems to be an issue with the fonts.

Is there any way I can get around this ?

**Comment by josiasmontag** [comment]
Please note that this is an issue trucker and not meant to be used for support requests.
As a CloudConvert customer, you can contact support@cloudconvert.com.
