### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by KnorpelSenf** [cloudconvert/cloudconvert-node#85]
Are there any plans to support the Deno runtime (https://deno.land)?

If so, how should this be done?

1. Create a third-party client for it
2. Create an official client for it
3. Add the tooling to this repo which allows both the client for Node and the client for Deno to be generated from the same source
4. Something else?

**Comment by josiasmontag** [comment]
I think 2. should be doable. The "main thing" of socket.io is all this fallback functionality to polling. We don't need that in a server side package - sending the raw messages via websocket should be fine.

**Comment by KnorpelSenf** [comment]
Perfect. Deno supports websockets natively via Web API. Still not sure if I want to invest the time, but it sounds indeed feasible

**Comment by KnorpelSenf** [comment]
Use `npm:` imports. See https://github.com/cloudconvert/cloudconvert-node/pull/87#issuecomment-1243509424 for more information. Closing.
