### ISSUE TITLE
Hook into localhost

### ISSUE THREAD

**Issue by RobbertWolfs** [cloudconvert/cloudconvert-node#9]
Since there is no cloudconvert github and we are using node.js in our project I'm going to ask it here.

Is there any way we can hook (https://cloudconvert.com/api/hooks) into localhost or use localhost as callback for development purpose?

Thanks in advance.

**Comment by josiasmontag** [comment]
This is technically not possible because our servers cannot access your localhost. You could use a tunnel solution like [ngrok](https://ngrok.com/).

**Comment by RobbertWolfs** [comment]
Thanks for the quick response 👍 .

I'll try ngrok :)

**Comment by RobbertWolfs** [comment]
Works like a charm 💯
