### ISSUE TITLE
'name' property missing on Task interface?

### ISSUE THREAD

**Issue by lennartnederstigt** [cloudconvert/cloudconvert-node#90]
From my, admittedly limited, testing of this SDK it seems that the `name` property of a task is also returned whenever you subscribe to task events via the `cloudConvert.jobs.subscribeTaskEvent` method.

I had a look at the API documentation and https://cloudconvert.com/api/v2/tasks#tasks-show doesn't mention returning the `name` property either. However, whenever I call that endpoint I do get the `name` property in the response as well.

Are the API documentation and the `Task` interface incomplete or shouldn't the API return the `name` property?

**Comment by josiasmontag** [comment]
The `name` property is only available if the task is part of a job. Tasks without any job do not have a name.

So strictly speaking the API docs should also describe the `name` property.

**Comment by lennartnederstigt** [comment]
Ah, thanks for the clarification! So in short, if I subscribe to events via `cloudConvert.jobs.subscribeTaskEvent` I can be certain that the tasks will have the `name` property, as they're obviously part of a job? Would be nice if the TS interface would include the `name` property in that case.

**Comment by KnorpelSenf** [comment]
I created the interfaces from the documentation. I think it's easier to keep the types up to date if they correspond exactly with the documentation on the website.

I'll happily add this option as soon as the website gets updated.

**Comment by josiasmontag** [comment]
The docs have been updated.
